config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root to: 'welcome#index'

  resources :users, only: [:update, :show]
  
  resources :lists, except: [:index] do
    resources :items, only: [:create]
  end

  resources :items, only: [:show, :destroy]

  get 'about' => 'welcome#about'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :list

  default_scope {order('created_at ASC')}

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]

  has_one :list, dependent: :destroy
  has_many :items, dependent: :destroy

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    if current_user.list
      current_user.list
    else
      new_list_path
    end
  end

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        @existing_user = User.find_by(email: @user.email)
        if @existing_user!=nil? && @existing_user.provider!=nil
          sign_in_and_redirect @user
        else
          flash[:error] = "Email already exists"
          redirect_to root_path
        end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  respond_to :html, :js

  def new
    @item = Item.new
  end

  def create
     @list = current_user.list
     @item = current_user.items.build(params.require(:item).permit(:name))
     @item.list_id = @list.id
     if @item.save
       flash[:notice] = "Item was saved."
       redirect_to @list
     else
       flash[:error] = "There was an error saving the item. Please try again."
       redirect_to @list
     end
  end

  def destroy
    @item = Item.find(params[:id])
    @list = @item.list
      
      if @item.destroy
        flash[:notice] = "\"#{@item.name}\" item was completed/deleted."
      else
        flash[:error] = "There was an error completing/deleting the item."
      end

    respond_with(@item) do |format|
      format.html { redirect_to @list }
    end 
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def show
    @list = current_user.list
    @item = Item.new
    @items = current_user.items
  end

  def new
    @list = List.new
  end

  def create
     @list = current_user.build_list(params.require(:list).permit(:title))
     if @list.save
       flash[:notice] = "List was saved."
       redirect_to @list
     else
       flash[:error] = "There was an error saving the list. Please try again."
       render :new
     end
  end

  def edit
     @list = current_user.list
  end

  def update
    @list = current_user.list
    if @list.update_attributes(params.require(:list).permit(:title))
      flash[:notice] = "List was updated."
      redirect_to @list
    else
      flash[:error] = "There was an error saving the list. Please try again."
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @title = @list.title
      
      if @list.destroy
        flash[:notice] = "\"#{@title}\" list was deleted successfully."
        redirect_to new_list_path
      else
        flash[:error] = "There was an error deleting the list."
        render :show
      end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
 
    def update
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       flash[:error] = "Invalid user information"
       redirect_to edit_user_registration_path
     end
    end
 
   private
 
  def show
    @user = current_user
    @items = current_user.items
  end

   def user_params
     params.require(:user).permit(:name)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<tr>
     <%= form_for [list, item] do |f| %>
       <td class="center vertical-center"><%=Time.now.strftime('%d-%b')%></td>
       <td class="form-group">
         <%= f.text_field :name, class: 'form-control', placeholder: "Add new item" %>
       </td>
       <td class="center vertical-center">7</td>
       <td class="form-group vertical-center center">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </td>
     <% end %>
</tr>

app/views/items/_item.html.erb
<%= content_tag :tr, class: 'media', id: "item-#{item.id}" do %>
            <td class="vertical-center center" style="width:100px"><%= item.created_at.strftime('%d-%b') %></td>
            <td><%= item.name %></td>
            <td class="vertical-center center"><%= (((item.created_at + 7.days) - Time.now)/86400).round %></td>
            <td class="vertical-center center"><%= link_to "", item, method: :delete, class: 'glyphicon glyphicon-ok', remote: true %></td>
<% end %>

app/views/items/destroy.js.erb
 <% if @item.destroyed? %>
  $('#item-' +<%= @item.id %>).fadeOut(600);
<% else %>
  $('#item-' +<%= @item.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <div class="pull-right user-info">
   <% if current_user %>
        Hello <%= link_to ((current_user.name == "" || current_user.name == nil) ? current_user.email : current_user.name), root_path %>!
        <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
          <span class="glyphicon glyphicon-user"></span>
        <% end %>
        <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
          <span class="glyphicon glyphicon-log-out"></span>
        <% end %>
   <% else %>
     <%= link_to "Sign In", new_user_session_path %> or 
     <%= link_to "Sign Up", new_user_registration_path %>
   <% end %>
 </div>

    <% if flash[:notice] %>
     <div class="alert alert-success">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:notice] %>
     </div>
    <% elsif flash[:error] %>
     <div class="alert alert-danger">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:error] %>
     </div>
    <% elsif flash[:alert] %>
     <div class="alert alert-warning">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:alert] %>
     </div>
    <% end %>


<%= yield %>

</div>


</body>
</html>

app/views/lists/edit.html.erb
  <h2>Edit list</h2>
 
  <div class="row">
   <div class="col-md-4">
     <%= form_for @list do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter list title" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
  </div>

app/views/lists/new.html.erb
<div class="jumbotron todolist">
<h2>New To-Do list</h2>
 
  <div class="row">
   <div class="col-md-8">
     <%= form_for @list do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter list title" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
  </div>
</div>

app/views/lists/show.html.erb
<%if @list.nil? %>
  <div class="row">
    <div class="col-md-8">
          <%= link_to "New To-do List", new_list_path, class: 'btn btn-success' %>
        </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 todo">        
     <h2 class="center"><%= @list.title %></h2>
        <table style="width: 100%" class="table table-striped">
          <tr>
            <th class="vertical-center center">Created</th>
            <th class="vertical-center center">Description</th>
            <th class="vertical-center center">Days left</th>
            <th class="vertical-center center">Complete</th>
          </tr>
            <%= render @items %>
            <%= render partial: "items/form", locals: { list: @list, item: @item } %>
        </table>
      </div>
    </div>
  <div class="row media">
    <div class="col-md-4"> 
         <%= link_to "Edit list", edit_list_path(@list), class: 'btn btn-success' %>
         <%= link_to "Delete list", @list, method: :delete, class: 'btn btn-danger', data: {confirm:'Are you sure you want to delete this list?'} %>
      </div>
  </div>
<% end %>

app/views/users/show.html.erb
 <div class="row">
   <div class="col-md-8">
     <div class="media">
       <div class="media-body">
         <h2 class="media-heading"><%= @user %></h2>
       </div>
     </div>
   </div>
 </div>
</br>

 <div class="row">
   <div class="col-md-8">
         <%= render @items %>
   </div>
 </div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
    <br/>
    <div class="jumbotron">
      <h1>PendList</h1>
        <p>A self-destructing to-do list to keep you focused on the things that really matter.</p>
        <p> 
          <% if !current_user %>
            <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or 
            <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
            <p>
              <small>You can also</small>
            <%= link_to "Sign In with Facebook", 'users/auth/facebook', class: 'btn-facebook btn' %></p>
          <% else %>
            <%= link_to "Go to my list", current_user.list, class: 'btn btn-primary' %>
          <% end %>
        </p>
    </div>